#! /usr/bin/env python

import sys

headers = 'pez vectormath openctm glsw glew'
prefix = '../lib/'

def build(gc):

    if sys.platform == 'win32':
        libs = 'opengl32 gdi32'
    else:
        libs = 'X11 GL'

    glob = gc.path.ant_glob

    gc.program(
        source = glob('*.c'),
        includes = path_list(headers, prefix),
        lib = libs,
        use = 'ecosystem',
        defines = gc.env.COMMON_DEFS,
        target = 'fish')

def path_list(paths, prefix):
    paths = paths.split(' ')
    return map(lambda x:prefix+x, paths)
