#! /usr/bin/env python

import sys

def build(gc):

    if sys.platform == 'win32':
        excl = '**/Linux.c'
    else:
        excl = '**/Windows.c'

    glob = gc.path.ant_glob
    files = glob(
        incl = '**/*.c',
        excl = excl)
    dirs = glob(
        dir = True,
        src = False,
        excl = '.svn')
    gc.stlib(
        source = files,
        includes = dirs,
        defines = gc.env.COMMON_DEFS,
        target = 'ecosystem')